apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: metalnetworks-configuration
  annotations:
    # Set the annotations defining the maintainer, source, license, and description of your Configuration
    meta.crossplane.io/maintainer: Marques Johansson <marques@displague.com>
    meta.crossplane.io/source: github.com/displague/configuration-metalnetwork
    # Set the license of your Configuration
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Example Configuration demonstrating how to use the Equinix Metal provider to create network infrastructure, including a VLAN, Gateway with VRF, and IP Reservations.
    meta.crossplane.io/readme: |
      # MetalNetworks Configuration

      This is a simple example that demonstrates how to use the Equinix Metal provider to create network infrastructure, including a VLAN, Gateway with VRF, and IP Reservations.
spec:
  # (Optional) Set the minimum version of Crossplane that this Configuration is compatible with
  crossplane:
    version: ">=v1.14.1-0"
  # Add your dependencies here
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-equinix
      version: "v0.6.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: "v0.3.0"
