apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: metalnetworks.equinix.xrds.crossplane.io
spec:
  group: equinix.xrds.crossplane.io
  names:
    kind: MetalNetwork
    listKind: MetalNetworkList
    plural: metalnetworks
    singular: metalnetwork
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vrfName:
                  type: string
                  description: "Name of the VRF"
                projectID:
                  type: string
                  description: "Equinix Metal Project ID"
                description:
                  type: string
                  description: "Description of the VRF"
                metro:
                  type: string
                  description: "Metro area for the VRF"
                ipPrefixes:
                  type: array
                  items:
                    type: string
                  description: "IP prefixes for the VRF"
                  default: ["192.168.100.0/24"]
                vxlan:
                  type: integer
                  description: "VXLAN ID for the VRF"
                  default: 1000
              required:
                - vrfName
                - projectID
                - metro
            status:
              type: object
              properties:
                vlanID:
                  type: string
                vrfID:
                  type: string
                gatewayID:
                  type: string
                ipReservationID:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
  claimNames:
    kind: MetalNetworkClaim
    plural: metalnetworkclaims
